export const DATA = [
  {
    id: '123Gyz',
    title: 'en salchichoneria',
    product: 'Harley Pompadoury',
    currency: '$',
    reward: '400',
    status: 'STACK',
    displayType: 'STACK',
    totalReward: 5000,
    totalTasks: 40,
  },
  {
    id: '123xyz',
    title: 'en infusiones',
    product: 'Harley Pompadour',
    currency: '¢',
    reward: '40',
    status: 'AVAILABLE',
    displayType: null,
    totalReward: null,
    totalTasks: null,
  },
  // {
  //   id: '223abd',
  //   title: 'Panadería',
  //   product: 'Horley Pompadour',
  //   currency: '¢',
  //   reward: '150',
  //   dueTime: '11:59 a.m.',
  //   status: 'RESERVED',
  //   cancelDisabled: true,
  // },
  // {
  //   id: '123abz1',
  //   title: 'Shopper',
  //   product: 'Walmart Querétaro',
  //   reward: '150',
  //   currency: '¢',
  //   status: 'RESERVED',
  //   pickingAndDelivery: {
  //     orderStatus: 'SHOPPER_OPEN',
  //     orderId: '12345-6789',
  //     pickingTime: '03:15 p.m.',
  //     deliveryTime: '05:15 p.m.',
  //     onTime: null,
  //     cancelEnabled: null,
  //   },
  // },
  // {
  //   id: '223abre',
  //   title: 'en cervezas',
  //   product: 'Grupo Modelo',
  //   reward: '150',
  //   dueTime: '9:00 p.m.',
  //   status: 'PENDING',
  // },
  // {
  //   id: '223abree',
  //   title: 'en cervezas',
  //   product: 'Grupo Modelo',
  //   reward: '150',
  //   dueTime: '9:00 p.m.',
  //   status: 'PENDING',
  // },
  // {
  //   id: '223abd1',
  //   title: 'Lácteos',
  //   product: 'Lala',
  //   reward: '150',
  //   store: 'Asturias',
  //   dueTime: '',
  //   status: 'RESERVED_BY_ME',
  //   cancelDisabled: true,
  // },
  // {
  //   id: '123abc',
  //   title: 'Shopper',
  //   product: 'Walmart',
  //   reward: '40',
  //   status: 'DISABLED',
  //   text: 'Tarea exclusiva para Zubaleros cool',
  // },
  // {
  //   id: '123abf',
  //   title: 'en carnes frias',
  //   product: 'Horley Pompadour',
  //   reward: '150',
  //   status: 'JUST_RESERVED_BY_OTHER',
  // },
  // {
  //   id: '123abe',
  //   title: 'en abarrotes',
  //   product: 'Horley Pompadour',
  //   reward: '150',
  //   status: 'RESERVED_BY_OTHER',
  // },
  // {
  //   id: '123abg',
  //   title: 'en limpieza',
  //   product: 'Horley Pompadour',
  //   reward: '150',
  //   taskLimit: 16,
  //   status: 'LIMIT',
  // },
  // {
  //   id: '123aby',
  //   title: 'Picker',
  //   product: 'Walmart La Concha',
  //   reward: '150',
  //   taskLimit: 8,
  //   status: 'LIMIT_WALMART',
  // },
  // {
  //   id: '123aby1',
  //   title: 'Picker',
  //   product: 'Walmart Universidad',
  //   reward: '150',
  //   status: 'WALMART',
  // },
  // {
  //   id: '123abz9',
  //   title: 'Shopper',
  //   product: 'Walmart Querétaro',
  //   reward: '150',
  //   status: 'SHOPPER',
  //   pickingAndDelivery: {
  //     orderStatus: 'SHOPPER_OPEN',
  //     orderId: '12345-6789',
  //     pickingTime: '03:15 p.m.',
  //     deliveryTime: '05:15 p.m.',
  //     onTime: null,
  //     cancelEnabled: null,
  //   },
  // },
  //WALMART TASK RESERVED BY ME
  // {
  //   id: '213abd1',
  //   title: 'Shopper',
  //   product: 'Walmart San Rafael',
  //   reward: '888',
  //   dueTime: '',
  //   status: 'SHOPPER_RESERVED_BY_ME',
  //   pickingAndDelivery: {
  //     orderId: '123probando',
  //     orderStatus: 'SHOPPER_OPEN',
  //     pickingTime: '03:15 p.m.',
  //     deliveryTime: '05:15 p.m.',
  //     address: 'Eugenio Zue 316, Polanco',
  //     cancelEnabled: true,
  //     cancelTime: 'una hora',
  //   },
  // },
  // {
  //   id: '123abs2',
  //   title: 'Shopper',
  //   product: 'Walmart San Cosme',
  //   reward: '150',
  //   status: 'SHOPPER',
  //   pickingAndDelivery: {
  //     orderStatus: 'SHOPPER_STARTED',
  //     orderId: '12345-6789',
  //     pickingTime: '03:15 p.m.',
  //     deliveryTime: '05:15 p.m.',
  //     onTime: false,
  //     cancelEnabled: true,
  //     cancelTime: '60 minutos',
  //   },
  // },
  // {
  //   id: '123abz2',
  //   title: 'Shopper',
  //   product: 'Walmart Buenavista',
  //   reward: '150',
  //   status: 'SHOPPER',
  //   pickingAndDelivery: {
  //     orderStatus: 'SHOPPER_STARTED',
  //     orderId: '12345-6789',
  //     pickingTime: '03:15 p.m.',
  //     deliveryTime: '05:15 p.m.',
  //     onTime: false,
  //     cancelEnabled: false,
  //   },
  // },
  // {
  //   id: '123abz3',
  //   title: 'Shopper',
  //   product: 'Walmart El Campo',
  //   reward: '150',
  //   status: 'SHOPPER',
  //   deepLinkButton: 'Ir a walmart app',
  //   inProgressMessage: 'Mensaje personalizable',
  //   pickingAndDelivery: {
  //     orderId: '123_probando',
  //     orderStatus: 'SHOPPER_IN_PROGRESS',
  //     pickingTime: '03:15 p.m.',
  //     deliveryTime: '05:15 p.m.',
  //     onTime: false,
  //     cancelEnabled: true,
  //     manualEnd: 'Terminar manual',
  //   },
  // },
  // {
  //   id: '123abz4',
  //   title: 'Shopper',
  //   product: 'Walmart Del Sur',
  //   reward: '150',
  //   status: 'SHOPPER',
  //   pickingAndDelivery: {
  //     orderStatus: 'SHOPPER_DELIVERED',
  //     orderId: '12345-6789',
  //     pickingTime: '03:15 p.m.',
  //     deliveryTime: '05:15 p.m.',
  //     onTime: false,
  //     cancelEnabled: false,
  //   },
  // },
  //WALMART TASK CANCELED
  // {
  //   id: '123abz5',
  //   title: 'Shopper',
  //   product: 'Walmart Satelite',
  //   reward: '150',
  //   status: 'SHOPPER',
  //   penaltyMessage: 'Tu reserva ha sido cancelada por inactividad.',
  //   punishmentPeriod: ' No podrás usar el app hoy ni mañana',
  //   pickingAndDelivery: {
  //     orderStatus: 'SHOPPER_CANCELED',
  //     orderId: '12345-6789',
  //     pickingTime: '03:15 p.m.',
  //     deliveryTime: '05:15 p.m.',
  //     onTime: false,
  //     cancelEnabled: false,
  //   },
  // },
  //CHEDRAUI
  // {
  //   id: '213ab45',
  //   title: 'Shopper',
  //   product: 'Chedraui Universidad',
  //   reward: '76',
  //   dueTime: '',
  //   status: 'CHEDRAUI_SHOPPER',
  //   pickingAndDelivery: {
  //     orderId: '213ab45213ab45',
  //     orderStatus: 'SHOPPER_OPEN',
  //     pickingTime: '03:15 p.m.',
  //     deliveryTime: '05:15 p.m.',
  //     address: 'Eugenio Zue 316, Polanco',
  //     cancelEnabled: true,
  //     cancelTime: 'una hora',
  //   },
  // },
  // {
  //   id: '223abe',
  //   title: 'en infusiones',
  //   product: 'Horley Pompadour',
  //   reward: '150',
  //   status: 'UNDER_REVIEW',
  // },
  // {
  //   id: '323abe',
  //   title: 'en infusiones',
  //   product: 'Horley Pompadour',
  //   reward: '150',
  //   status: 'COMPLETED',
  // },
  // {
  //   id: '423abe',
  //   title: 'en infusiones',
  //   product: 'Horley Pompadour',
  //   reward: '150',
  //   status: 'REJECTED',
  //   rejectionReason:
  //     'Las fotos del anaquel están borrosas y no se ven los precios en las etiquetas',
  // },
];
